[project]
name = example_pycusat
version = 0.0.1
authors = [
  { name=Example Author, email=author@example.com },
]
description = A small example package
readme = README.md
requires-python =  Language :: Python :: 3,
    License :: OSI Approved :: MIT License,
    Operating System :: OS Independent,
]

[project.urls]
Homepage = https://github.com/aswinpradeepc/test
Issues = https://github.com/aswinpradeepc/test/issues

